include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      es01:
        condition: service_healthy
    image: ragflow:latest
    container_name: ragflow-server
    ports:
      - 9999:9999
    networks:
      - ragflow
    restart: always

